server:
  port: ${SERVER_PORT:8080}

logging:
  level:
    reactor.netty: DEBUG
    org.springframework.cloud.gateway: TRACE
    ru.achernyavskiy0n.apigateway: DEBUG
spring:
  cloud:
    gateway:
      routes:
        - id: news-delivery
          uri: ${NEWS_HOST:http://localhost:8083}
          order: 10
          predicates:
            - Path=/api/v1/news/**
            - Method=POST
        - id: opeartions
          uri: ${OPERATION_HOST:http://localhost:8084}
          order: 8
          predicates:
            - Path=/api/v1/operations/**
            - Method=POST
      httpclient:
        wiretap: true
      httpserver:
        wiretap: true

api-gateway:
  hosts:
    news-delivery-host: ${NEWS_HOST:http://localhost:8083}
    operation-manager-host: ${OPERATION_HOST:http://localhost:8084}
jwt:
  publicKey: ${JWT_PUBLIC_KEY}
